name: Label Dependabot PR Risk

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - "*.gradle"

jobs:
  label-risk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install requests pyyaml packaging

      - name: Run risk label script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/label_risk.py
